version: "3.11"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Siker-bet/model:/app/model  # solo montamos la carpeta de modelos
