# fly.toml app configuration file generated for sikerbet on 2023-07-26T19:10:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sikerbet"
primary_region = "mad"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
