# fly.toml app configuration file generated for sikerbet on 2023-10-11T19:02:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sikerbet"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
